config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'home_page#index'
    get 'home_page/show/:hash', to: 'home_page#show', as: 'home_page_show'

    get 'accounts/index'
    get 'accounts/show'

    get 'assets/index'
  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '/', to: redirect("/#{I18n.default_locale}")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @page = params[:index].present? ? params[:index] : 0
    if @page.to_i < 0
      @page = 0
    end

    response = RestClient.get('http://localhost:9090/explorer/api/v1/accounts', {accept: :json, params: { page: @page }})
    @accounts = JSON.parse(response.body)

    response = RestClient.get('http://localhost:9090/explorer/api/v1/asset-definitions/as-string', {accept: :json})
    @asset_definitions = JSON.parse(response.body)
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    @page = params[:index].present? ? params[:index] : 0
    if @page.to_i < 0
      @page = 0
    end

    response = RestClient.get('http://localhost:9090/explorer/api/v1/asset-definitions', {accept: :json, params: { page: @page }})
    @asset_definitions = JSON.parse(response.body)
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @page = params[:index].present? ? params[:index] : 0
    if @page.to_i < 0
      @page = 0
    end
    response = RestClient.get('http://localhost:9090/explorer/api/v1/blocks', {accept: :json, params: { page: @page }})
    @blocks = JSON.parse(response.body)
  end

  def show
    hash = params[:hash]
    response = RestClient.get('http://localhost:9090/explorer/api/v1/transactions', {accept: :json, params: { hash: hash }})
    @transaction = JSON.parse(response.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_prev_button(page)
    if controller_name == "home_page"
      return link_to root_url(index: (@page.to_i - 10)), class: "page-link" do
        t("previous")
      end
    elsif controller_name == "accounts"
      return link_to accounts_index_url(index: (@page.to_i - 10)), class: "page-link" do
        t("previous")
      end
    else
      return link_to assets_index_url(index: (@page.to_i - 10)), class: "page-link" do
        t("previous")
      end
    end
  end

  def render_next_button(page)
    if controller_name == "home_page"
      return link_to root_url(index: (@page.to_i + 10)), class: "page-link" do
        t("next")
      end
    elsif controller_name == "accounts"
      return link_to accounts_index_url(index: (@page.to_i + 10)), class: "page-link" do
        t("next")
      end
    else
      return link_to assets_index_url(index: (@page.to_i + 10)), class: "page-link" do
        t("next")
      end
    end
  end

  def get_instruction(instruction)
    case
    when instruction["transferBox"].present?
      "Transfer Asset"
    when instruction["registerBox"].present?
      object = instruction["registerBox"].to_s
      if object.include? "newAccount"
        "Register Account"
      elsif object.include? "newAssetDefinition"
        "Register Asset Definition"
      elsif object.include? "asset"
        "Register Asset"
      elsif object.include? "newDomain"
        "Register Domain"
      elsif object.include? "newRole"
        "Register Role"
      elsif object.include? "validtor"
        "Register Validator"
      elsif object.include? "definition"
        "Register Permission"
      elsif object.include? "peer"
        "Register Peer"
      else
        "Register"
      end
    when instruction["unregisterBox"].present?
      object = instruction["unregisterBox"].to_s
      if object.include? "assetId"
        "Unregister Asset"
      elsif object.include? "accountId"
        "Unregister Account"
      elsif object.include? "domainId"
        "Unregister Domain"
      elsif object.include? "assetDefinitionId"
        "Unregister Asset Definition"
      elsif object.include? "peerId"
        "Unregister Peer"
      elsif object.include? "triggerId"
        "Unregister Peer"
      elsif object.include? "roleId"
        "Unregister Role"
      elsif object.include? "permissionTokenDefinitionId"
        "Unregister Permission Token"
      elsif object.include? "validatorId"
        "Unregister Validator"
      else
        "Unregister"
      end
    when instruction["grantBox"].present?
      "Grant Access"
    when instruction["revokeBox"].present?
      "Revoke Access"
    when instruction["mintBox"].present?
      "Mint Asset"
    when instruction["burnBox"].present?
      "Burn Asset"
    else
      "Unknown"
    end
  end
end

app/views/accounts/index.html.haml
#account-page
  .container
    .row
      .col-md-12
        .m-t-25
        .sorakh-panel
          .title
            %h4
              = t("accounts")
          .table-responsive
            %table.table
              %thead
                %tr
                  %th.sticky-cell{style: "width: 25%"}= t("account_name")
                  - @asset_definitions.each do |definition|
                    %th.text-center= definition
              %tbody
                - @accounts["data"]&.each do |account|
                  - account_assets = account["assets"]
                  - asset_hash = Hash.new
                  - account_assets.each do |asset|
                    - definition = asset[1]["id"]["definitionId"]
                    - quantity = asset[1]["value"].first[1]

                    - asset_definition_id = "#{definition["name"]["string"]}##{definition["domainId"]["name"]["string"]}"
                    - asset_value = quantity
                    - asset_hash[asset_definition_id] = asset_value
                  %tr
                    %td.sticky-cell= "#{account["id"]["name"]["string"]}@#{account["id"]["domainId"]["name"]["string"]}"
                    - @asset_definitions.each do |definition|
                      - balance = asset_hash[definition].present? ? (asset_hash[definition]) : 0.to_s
                      - balance = balance.to_s.include?("fixedPoint") ? balance["fixedPoint"] : balance
                      %td.text-center= balance

        = render "partials/pagination", data: @accounts

app/views/accounts/show.html.haml
%h1 Accounts#show
%p Find me in app/views/accounts/show.html.haml

app/views/assets/index.html.haml
#asset-definitions
  .container
    .row
      .col-md-12
        .m-t-25
        .sorakh-panel
          .title
            %h4= t("assets")
          .table-responsive
            %table.table
              %thead
                %tr
                  %th= t("definition")
                  %th= t("asset_type")
                  %th= t("mintable")
                  %th.text-center= t("circulating_supply")
                  %th.text-center= t("holders")
              %tbody
                - @asset_definitions["data"]&.each do |asset_definition|
                  %tr
                    %td= asset_definition["assetDefinitionId"]
                    %td= asset_definition["type"]
                    %td= asset_definition["mintable"]
                    %td.text-center= asset_definition["circulatingSupply"]
                    %td.text-center= asset_definition["holders"]
                    


        = render "partials/pagination", data: @asset_definitions

app/views/home_page/_block.html.haml
- block_header = block["header"]
- block_valid_transactions = block["transactions"]
- block_rejected_transactions = block["rejectedTransactions"]

.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "BlockModal#{block_header["height"]}Label", id: "BlockModal#{block_header["height"]}", tabindex: "-1"}
  .modal-dialog.modal-xl
    .modal-content.sorakh-modal-content
      .modal-header
        %h1.modal-title.fs-5{id: "BlockModal#{block_header["height"]}"}
          = t("block_detail")
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      .modal-body
        .row.block-detail
          .col-md-3
            %p.text-muted= t("height")
          .col-md-9
            = block_header["height"]
        %hr.divider-line
        .row.block-detail
          .col-md-3
            %p.text-muted= t("timestamp")
          .col-md-9
            = Time.at((block_header["timestamp"].to_i)/1000)

        %hr.divider-line
        .row.block-detail
          .col-md-3
            %p.text-muted= t("hash")
          .col-md-9
            = block_header["currentBlockHash"]["array"]
        
        %hr.divider-line
        .row.block-detail
          .col-md-3
            %p.text-muted= t("prev_hash")
          .col-md-9
            = block_header["previousBlockHash"]["array"]
        
        %hr.divider-line
        .row.block-detail
          .col-md-3
            %p.text-muted= t("committed")
          .col-md-9
            = block_valid_transactions&.size

        %hr.divider-line
        .row.block-detail
          .col-md-3
            %p.text-muted= t("rejected")
          .col-md-9
            = block_rejected_transactions&.size
        %br/
        %br/

app/views/home_page/index.html.haml
#home-page
  .container
    .row
      .col-md-12
        .m-t-25
        .sorakh-panel
          .title
            %h4= t("blocks")
          .table-responsive
            %table.table
              %thead
                %tr
                  %th= t("height")
                  %th= t("timestamp")
                  %th= t("hash")
                  %th.text-center= t("status")
              %tbody
                - @blocks["data"]&.each do |block|
                  - block_header = block["header"]
                  - block_valid_transactions = block["transactions"]
                  - transaction_hash = block_valid_transactions&.size != 0 ? block_header["transactionsHash"]["hash"]["array"] : block_header["rejectedTransactionsHash"]["hash"]["array"]
                  %tr
                    %td
                      = link_to block_header["height"], home_page_show_url(hash: transaction_hash), class: "text-muted"
                    %td.text-muted= Time.at((block_header["timestamp"].to_i)/1000)
                    %td= block_header["currentBlockHash"]["array"]
                    %td.text-center.parent-status
                      .transaction-status__icon{class: (block_valid_transactions&.size != 0 ? "committed" : "rejected")}
                        - if block_valid_transactions&.size != 0
                          %svg{fill: "none", viewbox: "0 0 14 10", xmlns: "http://www.w3.org/2000/svg"}
                            %path{d: "M5 10c.42 0 .79-.15 1.1-.44l7.44-7.06c.3-.3.46-.64.46-1.03 0-.4-.15-.76-.46-1.05-.3-.28-.66-.42-1.09-.42-.43 0-.8.14-1.1.42L5.02 6.41l-.03.01-.03-.01-2.3-2.18a1.46 1.46 0 0 0-.51-.32 1.48 1.48 0 0 0-.59-.12c-.44 0-.8.14-1.1.42-.15.14-.26.3-.35.48a1.41 1.41 0 0 0 .35 1.6l3.43 3.27c.3.3.67.44 1.1.44Z", fill: "currentColor"}
                        - else
                          %svg{fill: "none", viewbox: "0 0 12 12", xmlns: "http://www.w3.org/2000/svg"}
                            %path{d: "M11 11c.29-.29.43-.63.43-1.04 0-.4-.14-.74-.43-1.03L8.62 6.55A.73.73 0 0 1 8.39 6c0-.22.08-.4.23-.56L11 3.07c.29-.29.43-.63.43-1.03S11.29 1.29 11 1A1.41 1.41 0 0 0 9.96.57c-.4 0-.74.14-1.03.43L6.55 3.38a.78.78 0 0 1-.55.24.78.78 0 0 1-.55-.24L3.07 1A1.41 1.41 0 0 0 2.04.57C1.64.57 1.29.71 1 1c-.29.29-.43.63-.43 1.04 0 .4.14.74.43 1.03l2.38 2.38c.15.15.23.34.23.56 0 .2-.08.39-.23.54L1 8.93c-.29.29-.43.63-.43 1.03s.14.75.43 1.04c.29.29.63.43 1.04.43.4 0 .74-.14 1.03-.43l2.38-2.38A.71.71 0 0 1 6 8.4c.21 0 .4.07.55.22L8.93 11c.29.29.63.43 1.03.43s.75-.14 1.04-.43Z", fill: "currentColor"}

        = render "partials/pagination", data: @blocks

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %meta{name: "author", content: "Vandy Sodanheang"}
    %meta{name: "description", content: "Iroha Block Explorer Built On Ruby On Rails"}

    %title Iroha Block Explorer
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render "partials/nav_bar"
    = yield

app/views/partials/_pagination.html.haml
%nav{"aria-label" => "Page navigation example"}
  %ul.pagination.sorakh-pagination
    - if @page.to_i > 1
      %li.page-item
        = render_prev_button(page: @page)
    - if (@page.to_i + 10) < data["total"].to_i 
      %li.page-item
        = render_next_button(page: @page)